In [1]:
import numpy as np

# 1. Create a 1D array containing numbers from 1 to 10
arr = np.arange(1, 11)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Sum of elements:", np.sum(arr))
print("Mean of elements:", np.mean(arr))
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data type: int64
Sum of elements: 55
Mean of elements: 5.5
Maximum value: 10
Minimum value: 1


In [2]:
import numpy as np

# Create two 3x3 matrices
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])

print("1. Matrix Addition:\n", np.add(A, B))
print("\n2. Matrix Subtraction:\n", np.subtract(A, B))
print("\n3. Element-wise Multiplication:\n", np.multiply(A, B))
print("\n4. Matrix Multiplication:\n", np.dot(A, B))

1. Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

2. Matrix Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

3. Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

4. Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## Q 3. Consider the marks of 5 students in 4 subjects.  
[[85,90,88,92], 
[70,65,72,68], 
[95,91,93,96], 
[60,75,70,80], 
[88,84,86,90]] 
Find: 
1. Average marks of each student 
2. Average marks of each subject 
3. Highest and lowest marks 
4. Student having the highest total marks

In [3]:
import numpy as np

# Marks of 5 students in 4 subjects
marks = np.array([[85, 90, 88, 92],
                  [70, 65, 72, 68],
                  [95, 91, 93, 96],
                  [60, 75, 70, 80],
                  [88, 84, 86, 90]])

# 1. Average marks of each student (mean across columns, axis=1)
avg_student = np.mean(marks, axis=1)

# 2. Average marks of each subject (mean across rows, axis=0)
avg_subject = np.mean(marks, axis=0)

# 3. Highest and lowest marks
highest_mark = np.max(marks)
lowest_mark = np.min(marks)

# 4. Student having the highest total marks
total_marks = np.sum(marks, axis=1)
best_student = np.argmax(total_marks) + 1  # Adding 1 for human-readable 1-based indexing

print("1. Average marks of each student:", avg_student)
print("2. Average marks of each subject:", avg_subject)
print("3. Highest mark:", highest_mark, "| Lowest mark:", lowest_mark)
print(f"4. Student having the highest total marks: Student {best_student}")

1. Average marks of each student: [88.75 68.75 93.75 71.25 87.  ]
2. Average marks of each subject: [79.6 81.  81.8 85.2]
3. Highest mark: 96 | Lowest mark: 60
4. Student having the highest total marks: Student 3


## 4. A grayscale image is represented by the following matrix. 
[[100,120,130], 
[150,180,200], 
[ 50, 80,100]] 
Perform: 
1. Normalize pixel values (divide by 255) 
2. Increase brightness by 30 
3. Clip values above 255 
4. Calculate average pixel intensity

In [4]:
import numpy as np

# Grayscale image matrix
image = np.array([[100, 120, 130],
                  [150, 180, 200],
                  [ 50,  80, 100]])

# 1. Normalize pixel values (divide by 255)
normalized_image = image / 255.0

# 2. Increase brightness by 30
brightened_image = image + 30

# 3. Clip values above 255
clipped_image = np.clip(brightened_image, a_min=0, a_max=255)

# 4. Calculate average pixel intensity
average_intensity = np.mean(image)

print("1. Normalized pixel values:\n", np.round(normalized_image, 4))
print("\n2. Increased Brightness (by 30):\n", brightened_image)
print("\n3. Clipped values (max 255):\n", clipped_image)
print("\n4. Average pixel intensity:", round(average_intensity, 2))

1. Normalized pixel values:
 [[0.3922 0.4706 0.5098]
 [0.5882 0.7059 0.7843]
 [0.1961 0.3137 0.3922]]

2. Increased Brightness (by 30):
 [[130 150 160]
 [180 210 230]
 [ 80 110 130]]

3. Clipped values (max 255):
 [[130 150 160]
 [180 210 230]
 [ 80 110 130]]

4. Average pixel intensity: 123.33


In [5]:
import numpy as np

# Monthly sales of 4 products over 6 months
sales = np.array([[120, 130, 140, 150, 160, 170],
                  [100, 110, 120, 130, 140, 150],
                  [150, 145, 160, 170, 180, 190],
                  [ 90, 100, 110, 120, 130, 140]])

# 1. Total sales of each product
total_sales_product = np.sum(sales, axis=1)

# 2. Average monthly sales of each product
avg_sales_product = np.mean(sales, axis=1)

# 3. Best-selling product
best_product = np.argmax(total_sales_product) + 1

# 4. Month with the highest overall sales
total_sales_month = np.sum(sales, axis=0)
best_month = np.argmax(total_sales_month) + 1

# 5. Standard deviation of sales for each product
std_dev_product = np.std(sales, axis=1)

print("1. Total sales of each product:", total_sales_product)
print("2. Average monthly sales of each product:", np.round(avg_sales_product, 2))
print(f"3. Best-selling product: Product {best_product}")
print(f"4. Month with the highest overall sales: Month {best_month}")
print("5. Standard deviation of sales for each product:", np.round(std_dev_product, 2))

1. Total sales of each product: [870 750 995 690]
2. Average monthly sales of each product: [145.   125.   165.83 115.  ]
3. Best-selling product: Product 3
4. Month with the highest overall sales: Month 6
5. Standard deviation of sales for each product: [17.08 17.08 15.92 17.08]
