In [1]:
!pip3 install numpy

In [7]:
import numpy as np #np---->industry level name
import time

arr = np.array([1, 2, 3, 4, 5])
print(arr , type(arr))  #nd---> n- dimensional arrray

[1 2 3 4 5] <class 'numpy.ndarray'>


In [1]:
#execution performance comparison 
size = 10_000_000 # 1 million data points

# python list
py_list = list(range(size)) #[1, 2, 3, 4, 5,..............till million]
start = time.time()
sq_list = [x**2 for x in py_list] #loop runned for taking sq of each elements in the list
end = time.time()
print(f"Pyhton list execution time = {end-start}  seconds")

# numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr**2 # no loop---vectorization 
end = time.time()
print(f"Numpy arrays execution time = {end-start}  seconds")

NameError: name 'time' is not defined

In [11]:
#memory optimization of numpy arrays are better
import sys

print(f" Python list size = {sys.getsizeof(py_list) * len(py_list)}) bytes ")
print(f" Numpy array size = {np_arr.nbytes} bytes ")

 Python list size = 800000560000000) bytes 
 Numpy array size = 800000000 bytes 


In [20]:
#CREATING NUMPY ARRAYS with Python Lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype)
print(arr.shape) #shape--->dimension ---> here its 1D [TOTAL ELEMENTS]

arr2 = np.array([1, 2, 3, 4, 5, "prime"]) #numpy converted all in strings---homogeneous
print(arr2, type(arr2), arr2.dtype) # <U21--- "< (Little-endian)"---"U (Unicode String"---"21 (Length)-max no. of chars allowed for any element in this array."
print(arr2.shape) #shape--->dimension ---> here its 1D [TOTAL ELEMENTS]

arr2D = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape) # shape--(3 x 3)--( row X col)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
(5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
(6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [54]:
#CREATING NUMPY ARRAYS from scratch
arr1F = np.zeros((2,3)) #prefill with zero, float-default
print(arr1F, arr1F.shape)
                   #both shapes are of a 2D arr matrix (2x3)
arr1I = np.zeros((2,3), dtype = "int64") # i want it in integer-->typecasted
print(arr1I, arr1I.shape, "\n")

arr2 = np.ones((5, )) #prefill with one
print(arr2, arr2.shape, "\n") # shape--1D arr of size 5

arr3 = np.full((2,3), 100) #prefill with val---"100: Val I want to fill"
print(arr3, arr3.shape, arr3.dtype, "\n" ) #default is whatever val you enter int/float/etc

arr4 = np.eye(4) #identity matrix--->pass only single val
print(arr4, arr4.shape, "\n") #always on sq matrix

arr5 = np.arange(0, 11, 2) #range elements (start, end, step)
print(arr5, arr5.shape, "\n") # shape-1D arr of size 6 depends on step

arr6 = np.linspace(1, 100, 3) #evenly spaced arrays---(start,end, "equalmiddle vals")
                              #by-default-->float
print(arr6, arr6.shape,)# shape-1D arr of size 3 depends on "equalmiddle vals"

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[0 0 0]
 [0 0 0]] (2, 3) 

[1. 1. 1. 1. 1.] (5,) 

[[100 100 100]
 [100 100 100]] (2, 3) int64 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4) 

[ 0  2  4  6  8 10] (6,) 

[  1.   50.5 100. ] (3,)


In [63]:
#np.array Properties
arr = np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] )

print(arr.shape) # n-dimension (m X n)
print(arr.size) #total elements
print(arr.dtype) # data-type
print(arr.ndim) #no. of dimensions

float_arr = arr.astype(np.float64) # arr.astype--->typecasted from existing array
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [70]:
#Operations on np.array
arr = np.array( [ [1, 2, 3], [4, 5, 6] ] )
print(arr, arr.shape) # " 2 X 3 "

#RESHAPE
reshape = arr.reshape(3,2) # reshape happens only when size of arr is same , can't do it for 2X5 or 3X7
print(reshape, reshape.shape, "\n")

#FLATTEN
flatten = arr.flatten() # 2D----> 1D
print(flatten, flatten.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2) 

[1 2 3 4 5 6] (6,)


In [80]:
#INDEXING in numpy
# nums=[1, 2, 3 ,4, 5] #1D array
# print(nums[0]) #----->output=1

nums = np.array( [ [1, 2, 3], [4, 5, 6] ] ) #2D array
print(nums[0][2] , "\n")

#FANCY INDEXING
fancy = np.array( [1, 2, 3 ,4, 5] ) # vectorization---> SAW ARRAY AS WHOLE
idx=[0,2,4]
print(fancy[idx] , "\n")

#BOOLEAN INDEXING
arr = np.array( [1, 2, 3 ,4, 5] )

print(arr[arr > 2]) # condition is to print greater than element 2 in arr
print(arr[arr % 2 == 0 ]) # even elements
print(arr[arr % 2 != 0 ]) # odd elements

3 

[1 3 5] 

[3 4 5]
[2 4]
[1 3 5]


In [82]:
#SLICING
arr = np.array( [1, 2, 3 ,4, 5] )

print(arr[1:4]) #[ start, end, step]
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [87]:
#Copy in py_list VS View in numpy_array---->Slicing
        #py_list copies original array. No change in original array.
        #numpy_array views and makes changes in original array.

#copy in py_list
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3] # slice
print(sub_list)
sub_list[0] = 200 # assigned val 200 in 0th index of sublist
print(sub_list)
print(nums , "\n") #No change in original array

#view in numpy_array
nums = np.array( [1, 2, 3, 4, 5] )
sub_arr = nums[1:3] # slice    
                    # sub_arr = nums[1:3].copy() -------> ".copy()" ----> copies original arr but by viewing only
print(sub_arr)
sub_arr[0] = 200 # assigned val 200 in 0th index of sub array
print(sub_arr)
print(nums) #Original array changed

# sub_arr = nums[1:3].copy()


[2, 3]
[200, 3]
[1, 2, 3, 4, 5] 

[2 3]
[200   3]
[  1 200   3   4   5]


In [96]:
#Data types in numpy --- int,float, bool,complex no.s,strings(S or U), objects 
                            # It's NOT advisable to use Numpy to store string-data or object-data----> cuz, Numpy optimized for numerical computations
#complex numbers 
arr = np.array(3 + 2j)
print(arr, arr.dtype, "\n") # 3 ---> 64 bits , 2j ----> 64 bits, adds upto 128 bits for complex

arr1 = np.array(3 + 2j)
arr2 = np.array(5 + 2j)
print(arr1 + arr2)
print(arr1 - arr2, "\n")

#object---> when heterogeneous data given , numpy considers it as object 
arr3 = np.array([ "PRIME", 3.14, {1, 2 , 3}])
print(arr3, arr3.dtype)


(3+2j) complex128 

(8+4j)
(-2+0j) 

['PRIME' 3.14 {1, 2, 3}] object


In [113]:
# MULTI-DIMENSIONAL ARRAYS

arr2D = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
print(arr2D, "\n")

print(np.sum(arr2D), "\n") # added all the elements 

sum_of_cols = np.sum( arr2D, axis = 0) # vertically ---> axis=0-->rows "har row me jake vertically operation perform ho rha"
print(sum_of_cols, "\n")

sum_of_rows = np.sum( arr2D, axis = 1) # horizontally ---> axis=1-->cols "har col me jake horizontally operation perform ho rha"
print(sum_of_rows, "\n")

print(arr2D[0:2, 1:2]) #slicing [2]  from 2D Array
                       #        [5]    
   
    #rows[start,end] , cols[start,end]
    # [ Row_Slice , Column_Slice ]

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

45 

[12 15 18] 

[ 6 15 24] 

[[2]
 [5]]


In [114]:
#3D ARRAY

arr3D = np.array([ [ [1, 2], [3, 4], [5, 6] ], [ [7, 8], [9, 10], [11, 12] ] ]) # ( 2 X 3 X 2 )----> ( no.of 2D arr , rows , cols)

print(arr3D, arr3D.dtype, arr3D.shape, "\n")

#indexing
print(arr3D[0, 2, 1] , "\n") # 2D array no. , row , col

#slicing
print(arr3D[:, 0, :])#row from both layers ---> depth(all) , row[0] for both , col(all)
print(arr3D[:, :, 0])#col from both layers ---> depth(all) , row[all] , col[0] for both
print("\n")

#performing operation by slicing
arr3D[:, 0, :] = 99 # assigning 99 at Oth row for both 2D arrays
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] int64 (2, 3, 2) 

6 

[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [26]:
#vectorization 

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr + arr2)

print("\n")
print(arr ** 2)
print(arr + 10)

[ 7  9 11 13 15]


[ 1  4  9 16 25]
[11 12 13 14 15]


In [24]:
#broadcasting
#---------Rules--1. Equal Dimensions 2.Either 1 3.Missing
arr = np.array([1, 2, 3, 4, 5]) #1D array
arr2 = np.array([ [1, 2, 3, 4, 5], [1, 2, 3, 4, 5] ]) #2D array

print(arr.shape)  #5
print(arr2.shape, "\n") #2 X 5

print(arr + arr2) # 5 matches 

#NOTE:- 3x2 and 5x2 can't be broadcasted. Even though 2 is same 3 and 5 not same
#       3x2 and 1x2 can be broadcasted. Even though 3 and 1 not same, but either one of them has 1

(5,)
(2, 5) 

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [20]:
# Vector Normalisation
#-------------->process of scaling the values within an array to a specific range, typically between 0 and 1.

arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr) # arr elements cancels out diagonally and gives mean = 0

print("\n")

print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


2.5
1.118033988749895
1.118033988749895


In [27]:
# Mathematical func
 
#aggregation

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) # calculates index of min val
print(np.argmax(arr)) # calculates index of max val

print(np.mean(arr))
print(np.std(arr)) # standard deviation = sqroot of variance
print(np.median(arr))
print(np.var(arr)) # variance

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [14]:
#power func 

arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3)) # here 3 is the power

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [3]:
#log & exponential func

arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

NameError: name 'np' is not defined

In [2]:
#rounding

print(np.round(3.14)) # round off to nearest
print(np.round(3.59))
print(np.ceil(3.14)) # round up bigger val
print(np.floor(3.14)) # round down 
print(np.trunc(3.14)) # evacuate after decimal

arr = np.array([1, 2, -8, 3, 4, -5, 2, -5])

print(np.unique(arr)) # like set()
print(np.sort(arr)) 
print(np.abs(arr)) # absolute vals---> turning -ve nums to +ve

NameError: name 'np' is not defined