In [4]:
import torch
import torch.nn as nn  #nn- alias/building block of neural networks

In [5]:
#input 
torch.manual_seed(42) #like random state->gives same output everytime(seed value fed)
inputs = torch.tensor([1.0, 2.0, 3.0]) #vector-1D array-> sent in float format
#tensor- multi-dimensional arrays used in pytorch

In [7]:
# pytorch does NOT have 'step' activation fnx
neuron = nn.Linear(in_features = 3 , out_features = 1) #Linear Activation fnx->cals weighted sum

In [8]:
output = neuron(inputs)

In [9]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [10]:
#verify ... formula(weighted sum)
# take dot product of input and weights + bias
neuron.weight @ inputs + neuron.bias  #'@'->dot product
#ans should be same with output

tensor([1.5244], grad_fn=<AddBackward0>)

In [11]:
neuron.weight # printing weights

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [12]:
neuron.bias # printing bias

Parameter containing:
tensor([0.5304], requires_grad=True)